apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf-service
spec:
  type: LoadBalancer # or LoadBalancer if you're on a cloud provider that supports it
  loadBalancerIP: 172.16.23.24
  selector:
    app: audiobookshelf
  ports:
  - port: 13378
    targetPort: 80
    protocol: TCP
    name: http
